projects:
  user:
    schema: graphql/User/schema.json
    documents: ./**/*.user.graphql
    extensions:
      languageService:
        useSchemaFileDefinitions: true
  admin:
    schema: graphql/Admin/schema.json
    documents: ./**/*.admin.graphql
    extensions:
      languageService:
        useSchemaFileDefinitions: true
  tenantAdmin:
    schema: graphql/TenantAdmin/schema.json
    documents: ./**/*.tenantAdmin.graphql
    extensions:
      languageService:
        useSchemaFileDefinitions: true
  api:
    schema: graphql/api/schema.json
    documents: ./**/*.api.graphql
    extensions:
      languageService:
        useSchemaFileDefinitions: true