declare namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_GRAPHQL_URL: string;
		NEXT_PUBLIC_API_URL: string;
		NEXT_PUBLIC_FIREBASE_EMULATOR: string;
		NEXT_PUBLIC_FIREBASE_API_KEY: string;
		NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
		NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
	}
}